version: '3.9'

services:
  database:
    container_name: database
    image: mysql:8.0.29
    platform: linux/x86_64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: db
      MYSQL_USER: symfony_user
      MYSQL_PASSWORD: symfony_pw
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app

  php:
    container_name: php
    build:
      context: ./docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./:/var/www/symfony
    networks:
      - app

  nginx:
    container_name: nginx
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/symfony:ro
    networks:
      - app

volumes:
  db-data:

networks:
  app: